version: '3.8'

services:
  moto:
    restart: always
    hostname: moto
    image: "motoserver/moto:4.1.6"
    ports:
      - 5000:5000

  fake-gcs:
    restart: always
    hostname: fake-gcs
    image: fsouza/fake-gcs-server:1.44
    command: >
      -scheme http
      -public-host ${URL:-localhost}:4443
    ports:
      - 4443:4443
    volumes:
      - ${PWD}/.gcs:/storage

  grpc-server:
    restart: always
    hostname: grpc-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    tty: true
    environment:
      AWS_SDK_LOAD_CONFIG: false
      AWS_PROFILE: default
      AWS_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: my-access-key
      AWS_SECRET_ACCESS_KEY: my-secret-key
      BUCKET_NAME: sample-bucket
      S3_ENDPOINT: http://moto:5000
      COGNITO_ENDPOINT: http://moto:5000
    volumes:
      - ./:/app
    working_dir: /app

  grpc-bff:
    restart: always
    hostname: grpc-bff
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    tty: true
    environment:
      GRPC_HOST: grpc-server:50051
      APP_HOST: http://localhost:3000
    volumes:
      - ./grpc-bff:/app
    working_dir: /app

  grpc-front:
    restart: always
    hostname: grpc-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    tty: true
    environment:
      GRPC_HOST: grpc-server:50051
    volumes:
      - ./grpc-front:/app
    working_dir: /app

  grpc-keycloak:
    restart: always
    hostname: grpc-keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    ports:
      - 8180:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --proxy=passthrough --hostname-strict=false
    volumes:
      - ./keycloak/config:/work
